lst = [
    'MI',
    'PA',
    'Karnataka',
    'TN',
    'WA',
    'Alabama',
    'GA',
    'AL',
    'Connecticut',
    'KY',
    'WI', 'Alberta',
    'North Carolina',
    'IN',
    'Texas',
    'Oregon',
    'TX',
    'CA',
    'Tennessee',
    'FL',
    'Rhode Island',
    'NJ',
    'Missouri',
    'FL - Florida',
    'NY',
    'MS',
    'Ga',
    'CT',
    'CO',
    'AZ',
    'DC',
    'MN',
    'IL',
    'Castries',
    'Ohio',
    'Virginia',
    'Wisconsin',
    'OR',
    'VA',
    'Default',
    'CDMX',
    'California',
    'IA',
    'Illinois',
    'MA',
    'Arizona',
    'Georgia',
    'Florida',
    'SC',
    'NEW YORK',
    'Colorado',
    'Michigan',
    'Tennessee (TN)',
    'New York',
    'District of Columbia',
    'Az',
    'Tamil Nadu',
    'Berlin',
    'Bogota',
    'Quebec',
    'NM',
    'tx',
    'DISTRITO CAPITAL',
    'OK',
    'Massachusetts',
    'Iowa',
    'State/Province',
    'Telangana',
    'Maharashtra',
    'NC',
    'oklahome',
    'Maryland',
    'Indiana',
    'ON',
    'kingston',
    'Kansas',
    'British Columbia',
    'il',
    'NE',
    'Southampton',
    'Ontario',
    'Metn',
    'AB',
    'Saskatchewan',
    'Fl',
    'california',
    'M',
    'OH',
    'MD',
    'ID',
    'NV',
    'AR',
    'Manitoba',
    'Nova Scotia',
    'UT',
    'Québec',
    'KS',
    'LA',
    'MO',
    'ME',
    'DE',
    'RI',
    'HI',
    'Prince Edward Island',
    'Pennsylvania',
    'Brooklyn',
    '23. Delaware County',
    'New Jersey',
    'Nevada',
    'New Hampshire',
    'Hawaii',
    'wi',
    'az',
    'TX - Texas',
    'ca',
    'South Carolina',
    'Ca',
    'Nebraska',
    'Iasi',
    'Washington',
    'fl',
    'Dc',
    'Kentucky',
    'Lagos',
    'Arkansas',
    'Pa',
    'Minnesota',
    'Delaware',
    'Oh',
    'mn',
    'SD',
    'TEXAS',
    'Selangor',
    'Alajuela',
    'Oakland County',
    'Not US or Canada',
    'Bulgaria',
    'Rizal',
    'Sd',
    'Metropolitana de Santiago',
    'Nc',
    'Oklahoma',
    'PR',
    'WV',
    'Federal Capital Territory',
    'East Sussex',
    'Canterbury',
    'Utah',
    'illinois',
    'Il',
    'Wi',
    'Wyoming',
    'New South Wales',
    'nevada',
    'Rye',
    '94108',
    '94104',
    '94063',
    '94107',
    '94588',
    '94080',
    '94105',
    '94103',
    '95131',
    '94706',
    '94612',
    '94025',
    '94066',
    '94404',
    '95050',
    '94304',
    '94401',
    '94111',
    '95113',
    '95054',
    '94086',
    '94545',
    '94402',
    '94608',
    '94403',
    '95138',
    '94065',
    '95035',
    '94538',
    '94118',
    '95110',
    '94102',
    '94002',
    '94015',
    '94104-4506',
    '94041',
    '94583',
    '94560',
    '94596',
    '95002',
    '94040',
    '94502',
    '94109',
    '94301',
    '94043',
    '94089',
    '95154',
    '95128',
    '95134',
    '94561',
    '95008',
    '94110',
    '94555',
    '95129',
    '94710',
    '94539',
    '94568',
    '94303',
    '94306',
    '95120',
    '94070',
    '95051',
    '94607',
    '94619-1627',
    '94087',
    '94121',
    '94085',
    '95037',
    'On',
    'Devon',
    'MB',
    'Gauteng',
    'BC',
    'PUNJAB',
    'Suffolk',
    'VIC',
    'Sulaymaniyah',
    'Other',
    'NSW',
    'NS',
    'Greater London',
    'METRO MANILA',
    '78',
    'Barcelona',
    '0',
    'WY',
    'North Island',
    'VT',
    'PE',
    'Nusa Tenggara Timur',
    'Middlesex',
    'Select From List',
    'Western Cape',
    'AK',
    'Madhya Pradesh',
    'Worcestershire',
    'None/Other',
    'CMX',
    'Nogota',
    'Vienna',
    'AA',
    'Outside the US or Canada',
    'QLD',
    'SK',
    'Bs as',
    'jakarta',
    'KZN',
    'Sindh',
    'Louisiana',
    'Dhaka',
    'GU',
    'NH',
    'Kerala',
    'SP',
    'Select One',
    'Hampshire',
    'Buckinghamshire',
    'London',
    'mazowieckie',
    'Scotland',
    'Sk',
    'Canada',
    'Victoria',
    'Noord Brabant',
    'Mi',
    'Singapore',
    'Md',
    'ND',
    'Uusimaa',
    'Tx',
    '4/27/20 9:21',
    'MQ',
    'Metro Manila',
    '95136',
    '95123',
    '95401',
    '95160',
    'Cundinamarca',
    'QA',
    'Auckland',
    'Germany',
    'francois Chabot',
    'homabay',
    'BW',
    '94954',
    'LA - Louisiana',
    'San Francisco',
    'St Michael',
    'Bursa',
    'Poland',
    'Province',
    'qc',
    'Mexico',
    'Idaho',
    'Madrid',
    'Lusaka',
    'Kuwait',
    'Hi',
    'New Zealand',
    'TBD',
    'MH',
    'Id',
    'New Jersery',
    'Neb',
    'Maine',
    'West Sussex',
    'MP',
    'Mississippi',
    'TN - Tennessee',
    'Abu Dhabi',
    'Ma',
    'Kigali',
    'Vermont',
    'International',
    'Cornwall',
    'Multnomah',
    'utah',
    'Ri',
    'ILLINOIS',
    'sc',
    '30',
    'New york',
    '3. Free State – 25 October 2022',
    'Baltimore',
    '.',
    'Chamkarmon',
    'Philippines',
    'tn',
    'Americas',
    'ga',
    'ny',
    '—',
    'Israel',
    'new york',
    'calif',
    'United States of America',
    'Delhi',
    'Montana',
    'Ny',
    'Co',
    'wa',
    'North Dakota',
    'Aargau',
    'Malaysia',
    'United States',
    'clifton',
    'Puerto Rico',
    'Kuala Lumpur',
    'Porto',
    'CALIFORNIA',
    'West Bengal',
    'HCM',
    'Western Province',
    'Mt',
    'nv',
    'israel',
    'Western Australia',
    'Tn',
    'Plano',
    'Nor',
    'Donegal',
    'Haryana',
    'KENTUCKY',
    'Massachussets',
    'new jersey',
    'Vietnam',
    'N.C.',
    'Punjab',
    'Dubai',
    'oh',
    'Hyogo',
    'SG',
    'Tunapuna Piarco',
    'Australia',
    'Arizons',
    'on',
    'Buenos Aires',
    'Caribbean',
    'United States/Canada',
    'CO - Colorado',
    'Nj',
    'Los Olivos',
    'Querétaro',
    'Ciudad Autónoma de Buenos Aires',
    'IL - Illinois',
    '5',
    'florida',
    'VI',
    'Rivers State',
    'JAMAICA',
    'Qatar',
    'Nassau County',
    'Chuy',
    'ma',
    'Nsw',
    'Austin',
    'State',
    'Atkins',
    'central',
    'noord holland',
    'IOWA',
    'Indupiana',
    'New Mexico',
    'texas',
    'Ky',
    'OHIO',
    'Southern States, LLC',
    'RHODE ISLAND',
    'Queensland',
    'St. Andrew',
    'georgia',
    'Canada (+1)',
    'ST',
    'Paraná',
    '94114',
    'Does not apply',
    'California (CA)',
    'South Dakota',
    'Ciudad AutÃ³noma de Buenos Aires',
    '94133',
    '94005',
    'South Australia',
    'OKLAHOMA (OK)',
    'Uttarakhand',
    'MT',
    'Mass',
    'lllinois',
    'Mo',
    'mo',
    'Essex',
    'Nairobi',
    'Central Singapore Community Development Council',
    'Malawi',
    'DENVER',
    'West Virginia',
    'England',
    'Gujarat',
    'Jamaica',
    'Yogyakarta',
    'Central Luzon',
    'Buenos Aires F.D.',
    'Mexico City',
    'San Jose',
    'Jiangsu',
    'Shanghai',
    'Alaska',
    'Bicol',
    'Al Asimah',
    'Ho Chi Minh City',
    'Central Region',
    'Guangdong',
    'Bangkok',
    'Macau',
    'Eastern Province',
    'Islamabad',
    'Seoul',
    'Central Singapore',
    'Tokyo',
    'Tel Aviv',
    'Liaoning',
    'Corrientes Province',
    'La Libertad',
    'Odisha',
    'Moscow',
    'Mimaropa',
    'Sao Paulo',
    'Central and Western',
    'Central District',
    'Jakarta',
    'Central Equatoria',
    'Kowloon City',
    'Australian Capital Territory',
    '95124',
    'Calabarzon',
    'NCT',
    'Minsk',
    'Jeju-do',
    'Kashmir',
    'Incheon',
    'Littoral',
    'Gu',
    'Guanajuato',
    'Cairo',
    'Uttar Pradesh',
    'New Brunswick',
    'Saint Catherine',
    'Amman',
    'Almaty Qalasy',
    'Bali',
    'Demerara-Mahaica',
    'Western',
    'Zakarpattia',
    'Goa',
    'Commune de Monaco',
    'Lima Province',
    'New Providence',
    'Woqooyi Galbeed',
    'Phra Nakhon Si Ayutthaya',
    'Al Madinah al Munawwarah',
    'Tsuen Wan',
    'Anasco',
    'Beijing',
    'Federal Capial &AJK',
    'Savanne',
    'Baladiyat ad Dawhah',
    'Grand Casablanca',
    'Rajasthan',
    'Santiago Metropolitan',
    'Banten',
    'Montevideo',
    'Ar Riyad',
    'Istanbul',
    'Makkah',
    'Krasnodarskiy',
    'Perak',
    'As Sulaymaniyah',
    'Yangon',
    'Parana',
    'West Bank',
    'South West',
    'Andhra Pradesh',
    'Quintana Roo',
    'Soufriere',
    'Penang',
    'Tunis',
    'Nairobi Area',
    'Osaka',
    'Addis Ababa',
    'Central Visayas',
    'Portland',
    'Baja California',
    'Jalisco',
    'Toshkent Shahri',
    'Guatemala',
    'Santiago',
    'Pulau Pinang',
    'Puebla',
    'Tibet Autonomous Region',
    'West Java',
    'Sumy',
    'Lviv',
    'object:1364',
    'Kyiv City',
    'Kingston',
    'Bogota D.C.',
    'Shandong',
    'Johor',
    'Moscow Oblast',
    'Daejeon',
    'Ha Noi',
    'Muhafazat Masqat',
    'Manchester',
    'Chisinau',
    'Kedah',
    'Southern Governorate',
    'Long An',
    "O'Higgins", 'Antioquia',
    'Tianjin',
    'Manama',
    'Baki',
    'Queretaro',
    'Taipei',
    'Ash Shariqah',
    'Delta',
    'Negeri Sembilan',
    'Izmir',
    'Asuncion',
    'Managua',
    'Atsinanana',
    'Maputo',
    'Nuevo Leon',
    'Nayarit',
    'Francisco Morazan',
    'Dar es Salaam',
    'Northern Region',
    'Toledo',
    '94618',
    'Chiba',
    'Coahuila',
    'Zhejiang',
    'Jaroslavl',
    'KwaZulu-Natal',
    'Capital',
    'va',
    'Kyoto',
    'Dushanbe',
    'Dakar',
    'Hai Phong',
    'Davao',
    "Leningradskaya Oblast'", 'Al Farwaniyah',
    'Vega Baja',
    'Jerusalem',
    'Santander',
    'Chandigarh',
    'lagos',
    'Rio de Janeiro',
    'Ankara',
    'Kanagawa',
    'Washington DC',
    'Sakhalin',
    'Hainan',
    'Yerevan',
    'Santo Domingo',
    'South Sinai',
    'Callao',
    'Taiwan',
    'Cordoba Province',
    'Region',
    'Red Sea',
    'Pernambuco',
    'Charlotte',
    'Tabasco',
    'Chon Buri',
    'Jharkhand',
    'Mugla',
    'Wanchai',
    'Okinawa',
    'St.-Petersburg',
    'Algiers',
    'Lima region',
    'Azuay',
    'Gyeongsangnam-do',
    'Bamako',
    'Michoacan',
    'Cagayan Valley',
    'Souhern Punajb Mulan',
    'Guizhou',
    'East Java',
    'Jilin',
    'Shaanxi',
    'Belize',
    'Poltava',
    'Kocaeli',
    'City of Port of Spain',
    'Hiroshima',
    'Tasmania',
    'Bolivar',
    'Beyrouth',
    'Haifa',
    'Heredia',
    'Kahramanmaras',
    'Other (outside US or Canada)',
    'Huila',
    'Anhui',
    'Santa Catarina',
    'Saint Ann',
    'Campeche',
    'Sichuan',
    'Manati',
    'Minas Gerais',
    'Ajman',
    'Manisa',
    'Phuket',
    'Atyrau',
    'Alexandria',
    'Harare',
    'National Capital',
    'Damietta',
    'Binh Thuan',
    'San Juan',
    'Chongqing',
    'Greater Accra',
    'Valle del Cauca',
    'Kharkiv',
    'Las Piedras',
    'San Salvador',
    'Va',
    'Panama',
    'Durango',
    'Kaafu Atoll',
    'Kinshasa',
    'Morelos',
    'Sonora',
    'Surat Thani',
    'East Kazakhstan',
    'Mendoza Province',
    'Khartoum',
    'Tuen Mun',
    'Sinoe',
    'Chaco Province',
    'Banaadir',
    'Centre',
    'Rio Grande do Sul',
    'Circonscription de Sigave',
    'GA - Georgia',
    'Abuja Federal Capital Territory',
    'FL/East',
    'La Pampa Province',
    '94566',
    'Northern District',
    'Mayorality of Baghdad',
    'Wellington',
    'Ica',
    'Baja California Sur',
    'Hubei',
    'Ulsan',
    'Beheira',
    'Newfoundland and Labrador',
    'Dorado',
    'Hunan',
    'Mayaguez',
    'Kabul',
    'Maritime',
    'Ponce',
    'Saint Michael',
    'Gyeongsangbuk-do',
    'Veracruz',
    'La Paz',
    'Central Serbia',
    'Amazonas',
    'North East',
    'Vojvodina',
    'California(CA)',
    'FLORIDA',
    'TENNESSEE',
    'D.C.',
    'Zh',
    'Europe',
    ' - None -',
    'La',
    'Adelaide, South Australia',
    'Washington, District of Columbia',
    'Oak Park, California',
    'Johannesburg',
    'San Jose, California',
    'Philadelphia, Pennsylvania',
    'Princeton, New Jersey',
    'Hartford, CT',
    'Toronto',
    'Mumbai, Maharashtra',
    'Sacramento, California',
    'Henderson, Maryland',
    'pa',
    'Tulsa, Oklahoma',
    'St Louis, Missouri',
    'Tampa, Florida',
    'San Francisco, California',
    'New York, New York',
    'Michigan City, Indiana',
    'Seattle, Washington',
    'Houston, Texas',
    'Tampa Bay, Florida',
    'Minneapolis, Minnesota',
    'Atlanta, Georgia',
    'New Haven, Indiana',
    'Owings Mills, Maryland',
    'Louisville, Kentucky',
    'Ypsilanti, Michigan',
    'University Park, Pennsylvania',
    'Ajax',
    'Oklahoma, Oklahoma',
    'Salem, Oregon',
    'El Paso, Texas',
    'Please select..',
    'Please select province',
    'Lincoln, Nebraska',
    'New Rochelle, New York',
    'Stone Mountain, Georgia',
    'Miami, Florida',
    'Phoenix, Arizona',
    'Middx',
    'Lorton, Virginia',
    'West Midlands',
    'Ile de France',
    'Vælg venligst region eller område',
    'Sweden',
    'Not in U.S. or Canada',
    'Noord Holland',
    'serbia',
    'District Of Columbia',
    'Los Angeles, California',
    'Melbourne Beach, Florida',
    'co',
    'Trinidad',
    'Mpumalanga',
    'Springfield, Massachusetts',
    'Sydney',
    'Albuquerque, New Mexico',
    'Makati',
    'Olive Branch, Mississippi',
    'Old Lyme, Connecticut',
    'Washington D.C.',
    'Palatine, Illinois',
    'Madison, Wisconsin',
    'INDIANA',
    'Urbana, Illinois',
    'Pichincha',
    'Durham',
    'MISSOURI',
    'Or',
    'São Paulo',
    'Netherlands',
    'Zurich',
    'Gampaha',
    'p',
    'CBD',
    'Ok',
    'SELANGOR DARUL EHSAN',
    'Středočeský kraj',
    'West Lothian',
    'ENG',
    'Notts',
    'United Kingdom/ Ireland',
    'United Kingdom',
    'Tirana',
    'Surrey',
    'Warwickshire',
    'Cheshire',
    'Austria',
    '1,001 - 5,000',
    'Por favor selecione',
    'Lancashire',
    'Monterrey',
    'CO 98-110-0775',
    'Stanford, California',
    'Eugene, Oregon',
    'Omaha, Nebraska',
    'OKlahoma',
    'Pittsburgh, Pennsylvania',
    'New Haven, Connecticut',
    'King of Prussia, Pennsylvania',
    'Wilayah Persekutuan',
    'uk',
    'Accra',
    'Ne',
    'SÃ£o Paulo',
    'Wa',
    'GEORGIA',
    'TELANGANA',
    'HK',
    'Company HQ State/Province',
    'Select',
    'Khorasan',
    'Kenya',
    'GA Georgia',
    'north carolina',
    'Meals on Wheels of Alameda County',
    'Angwin',
    'me',
    'BUENOS AIRES',
    'NEW JERSEY',
    'OH - Ohio',
    'Alpes Maritimes',
    'District of Comumbia',
    'England and Wales',
    'Dekalb',
    'Logan',
    'Ciudad Autonomas de Buenos Aires',
    'Outside US/Canada',
    'Select...',
    'Please select region, state or province',
    'Baden-Wuerttemberg',
    'GAUTENG',
    'US',
    'Bay of Plenty',
    'Estado de México',
    'missouri',
    'Ciudad de México',
    'Ct',
    'NORTH CAROLINA',
    '61838624',
    'Basel-City',
    'Lisbon',
    'Bavaria',
    'Ile-de-France',
    'VIRGINIA',
    'Munster',
    'Rheinland-Pfalz',
    'al',
    'Nouvelle-Aquitaine',
    'Tyne and Wear',
    'Berkshire',
    'Coamo',
    'buenos aires',
    'Leinster',
    'Hertfordshire',
    'Derby',
    'Doncaster',
    'Geneva',
    'Hessen',
    'South Holland',
    'Vaestra Goetaland',
    'Lower Austria',
    'Styria',
    'Stockholm',
    'Oxfordshire',
    'Groningen',
    'North Rhine-Westphalia',
    'Edinburgh',
    'Hesse',
    'Cambridgeshire',
    'Pathum Thani',
    'North Holland',
    'Dumfries and Galloway',
    'Kent',
    'Schwyz',
    'Hamilton city',
    'Utrecht',
    'Nordrhein-Westfalen',
    'mi',
    'Lombardy',
    'Neuchatel',
    'North Brabant',
    'Capital Region',
    'Catalonia',
    'Tyrol',
    'Flevoland',
    'Gyeonggi-do',
    'Vaud',
    'South Yorkshire',
    '15',
    'Cumbria',
    'County Londonderry',
    'Aberdeen City',
    'Subcarpathian Voivodeship',
    'Andalusia',
    'Balearic Islands',
    'Auvergne-Rhone-Alpes',
    'Yamaguchi',
    'Staffordshire',
    "Muhafazat al Jahra'", 'San Diego',
    'Cheshire West and Chester',
    'Akershus',
    'Schleswig-Holstein',
    'Torfaen County Borough',
    'Oslo',
    'Ulster',
    'San German',
    'TX-Texas(US)',
    'Uri',
    'Gotland',
    'Lower Saxony',
    'Brussels Capital',
    'Karn?taka',
    'Zug',
    'Bristol',
    'Vi',
    'Plaines Wilhems',
    "T'bilisi", 'Occitania',
    'Region Hovedstaden',
    'Schaan',
    'Melaka',
    'Pembroke',
    'Pays de la Loire',
    'DISTRITO FEDERAL',
    'michigan',
    'Leicestershire',
    'Salzburg',
    'Northamptonshire',
    'Flanders',
    'North Down District',
    'Schaffhausen',
    'Waikato',
    'Thuringia',
    'Lucerne',
    'Greater Manchester',
    'Latium',
    'South Denmark',
    'Limburg',
    'Piedmont',
    'Arecibo',
    'Lanca',
    'Galway',
    'ohio',
    'ky',
    'IO',
    'santa monica',
    'West VA',
    'Welch',
    'nj',
    'ks',
    'washington',
    'manitoba',
    'CHina',
    '76102-6847',
    'El Salvador',
    '75379',
    'DUBAI',
    'Los Angeles',
    'Doha',
    'frenchelle',
    'National Capital Region',
    'Regina',
    'CA - California',
    'oregon',
    'Saint-Petersburg',
    'West Bengal, India',
    'San Diego, California',
    'Select an option…',
    'United States (+1)',
    'Mansfield, Massachusetts',
    'MEX',
    'UGANDA',
    '1715',
    'swiss',
    'SOuth East',
    'Kwazulu Natal',
    'state is required for USA, Canada, and Mexico residents',
    'Orange, California',
    'PARAMARIBO',
    'AGUASCALIENTES',
    'WASHINGTON',
    'Torrance',
    'vermont',
    '750243502',
    'Al Raha Beach',
    'All Other States',
    'Maldives',
    'RM - Santiago',
    'V',
    "'-- Select --", 'Phnom Penh',
    'Western Area',
    'Southern Region',
    'Tobago',
    "Ra's al Khaymah", 'Central Governorate',
    'Yukon',
    'Guadalcanal',
    'Chittagong',
    'Mont-Liban',
    'Giza',
    'Chiang Mai',
    'Guerrero',
    'Saint James',
    'Noonu Atoll',
    'Federally Administered Tribal Areas',
    'Tehran',
    'Neuquen Province',
    'South-East',
    'Nyeri',
    'St Helier',
    'Atlantico',
    'Juana Diaz',
    'Siem Reap',
    'Raa Atoll',
    'Port Louis',
    'Luxor',
    'Bulawayo',
    'Kostroma',
    'Nord Kivu',
    'Region Metropolitana',
    'Khomas',
    'Tripoli',
    'South East',
    'Eastern Cape',
    'Chhattisgarh',
    'Enugu',
    'Bay of Plenty Region',
    'Dhaalu Atholhu',
    'Hhohho',
    'Muhafazat Hawalli',
    'Norhern Punajb Rawalpindi',
    'Central',
    'Pristina',
    'Laikipia',
    'Abidjan',
    'Maseru',
    'Sanaa',
    'Samara',
    'Sarawak',
    'Podgorica',
    'Putrajaya',
    'George Town',
    'Federation of Bosnia and Herzegovina',
    'Northern Territory',
    'Tirane',
    'Maule',
    'Shizuoka',
    'ct',
    'State/Province (US and Canada ONLY)',
    'Tamil Nadu / INDIA',
    'Morocco',
    'Lisboa',
    'vt',
    'Private customer',
    'Other / Non US',
    'QC',
    'PULAU PINANG',
    'Cebu',
    'Dublin',
    'Select prefecture',
    'QuÃ©bec',
    'kZN',
    'New Delhi',
    'Chennai',
    'Belfast',
    'Northampton',
    'Sandwell',
    'San Luis Potosi',
    'Hamburg',
    'Skane',
    'UK',
    'Hants',
    'Dorset',
    'Cambs',
    'Midlothian',
    'North Yorkshire',
    'na',
    'sofia',
    'BRITISH COLUMBIA',
    'Ut',
    'Mazowieckie',
    'c',
    'Mazovian',
    'Shawna',
    'F',
    'none',
    'LAGOS',
    'NCR 4th District',
    '????? ??????',
    'Western Area Urban',
    'KANSAS',
    ' -',
    'Nuevo LeÃ³n',
    'hong kong',
    'pA',
    'Douglas',
    'ZÃ¼rich',
    'nys',
    'no',
    'Riyadh',
    'Laos',
    'NCD',
    'df',
    'VERMONT',
    'OXon',
    'United Arab Emirates',
    'St Andrew',
    '14-604796-0',
    'U.S.',
    'dD',
    'Kano',
    'DCCdd',
    'Valencia',
    'Eleuthera',
    'OmOntario',
    'oOntario',
    'Mail M',
    'AlabamaA',
    'Denver',
    'Lekki',
    'United Kingdom (+44)',
    'Gelderland',
    "'-", 'DOHA',
    'Khobar',
    'Please select...',
    'heredia',
    'Francisco Moraz√°n',
    'MICHIGAN',
    'state',
    'West Indies',
    'NCR',
    'xx',
    'Marlborough',
    'Bermuda',
    'karnataka',
    'NENE',
    'NENne',
    'NENENE',
    'WiscomWI',
    'OhioOhio',
    'BNENE',
    'NEN',
    'idIIdaho',
    'D.F.',
    'Beirut',
    'St. Lucia',
    'Ont',
    'Banjul',
    'W Midlands',
    'Makkah Region',
    'Hauts de seine',
    'Renfrewshire',
    'Gros Islet',
    'Benguet',
    'Mn',
    'AP',
    'Wiltshire',
    'Gloucestershire',
    'Bath and NE Somerset',
    'BL',
    'Mid Lothian',
    'Lima',
    'ZH',
    ' - Select One -',
    'Tanzania, United Republic Of',
    'kuala lumpur',
    'Macedonia',
    'KA',
    'Uttar pradesh',
    'Üsküdar',
    'Ashgabat',
    'İstanbul',
    'Lodz',
    'Brussels',
    'Yorkshire',
    'AAR',
    'ff',
    ' --Select--',
    'West Indieswn',
    'WIW',
    'NAIROBI',
    'ErongoEsa100',
    'Test',
    'NYNew',
    'TriniTri',
    'Choose County',
    'CColoradoC',
    'Armed Forces Europe',
    'DF',
    'Select State',
    'MaMa',
    'i',
    'TC',
    'Pampanga',
    'Prague',
    'Offaly',
    'Montego Bay',
    'Meath',
    'Lj',
    'Hanoi',
    'Cluj',
    'Bucure?ti',
    'Budapest',
    'Bc',
    'Metropolitana',
    'Quezon City',
    'București',
    'Belgrade',
    'United States / Canada only',
    '9',
    'MOMOMMp',
    'bc',
    'St. Andred',
    'malopolska',
    'sd',
    'Grand Bassa County',
    'Bahamas',
    'CACA',
    'Zimbabwe',
    'P',
    'Hamilton',
    'B.C',
    'Christ Church',
    'cALIFORNIA',
    'BVI',
    'Gulshan',
    'MOUNTAIN PROVINCE',
    'Cambridge',
    'NIGER STATE',
    'Zambales',
    'Manila',
    'Texas (USA)',
    'Lagos State',
    'XC',
    '876',
    'IWIowa',
    'MMNMN',
    'VVA',
    'NB',
    'West Bekaa',
    'Yo  r kshire',
    'IN-KA',
    'Antrim',
    ' --',
    'Choose One...',
    'WA - Washington',
    'ari',
    'ROMANIA',
    'Portugal',
    'outside US',
    'Angola',
    'lancashire',
    'BARCELONA',
    'Guam',
    'Tamilnadu',
    'Country- Bermuda- not listed ion drop down menu',
    'Others',
    'Co Galway',
    'Couva',
    '[Outside US, Canada or AU]',
    'Chantal',
    'Vancouver',
    'Nairobi City',
    'TAS',
    'Kosovo',
    'quebec',
    'Aberdeenshire',
    'Dumfries & Galloway',
    'Bcau County',
    'KINGKIN0',
    'Mandalay',
    'Ukraine',
    't',
    'Nyanza',
    'Toluca',
    'N/a',
    'ONTARIO (ON)',
    'Ciudad de Mexico',
    'St. Michael',
    'Queensland, Australia',
    'Kosove',
    'Bled',
    'Vic',
    'MAHARASHTRA',
    'Glasgow',
    'Österreich',
    'Louth',
    'Ill',
    "'--None--", 'CA California',
    'Riga',
    'Oman',
    'Cataluña',
    'Ireland',
    'RIVERS',
    'nNJ',
    'NJ - New Jersey',
    "'- Select -", 'amMaasdfadfafMDmDMd',
    '?New YorknNY',
    'Krakow',
    'NRW',
    'Not available',
    'ALBERTA',
    'TeTX',
    'Bridgetown',
    'IllIL',
    'COLORADO',
    'Mexico city',
    'Yucatan',
    'Ar',
    'ma?opolska',
    'Cork',
    'NL',
    'Na',
    'Bruxelles-Capitale, Region de',
    'Virginia (VA)',
    'Balochistan',
    'sindh',
    'Kericho',
    'ontario',
    'Bucks.',
    'Texas (TX)',
    'ONTARION',
    'Pos',
    'CAca',
    'County (optional)',
    'Milwaukee',
    'Nasarawa Region',
    'Please Choose',
    'Hard',
    'Kogi',
    'Niger State',
    'Abuja',
    'FCT',
    'Ashburn, VA',
    'AMAC',
    'FCT Abuja',
    'TexTe',
    'East Harford',
    'nc',
    'Missouri (MO)',
    'Newtown Square',
    'fct Abuja',
    'ArlingtonATX',
    'Quito, Pichincha',
    'Clayton, MO',
    'Benguet CAR',
    'Abuja - FCT',
    'Ja',
    'aA',
    'KOGI',
    'Chicago',
    'cund',
    'MissourtyMMOM',
    'nebraska',
    'Rochest',
    'GREENVILLE',
    'Rosengarten',
    'Burlington, Vermont',
    'Sofiasof',
    'St MixhWL',
    'Boston MA',
    'KARNATAKA',
    'Sind',
    'Please Select',
    'Hochiminh',
    'Select option',
    'QB',
    'East Dunbartonshire',
    'Federal',
    'makkah',
    'MADRID',
    'Islington',
    'Simiyu',
    'Remote',
    'RJ',
    'Gwinnett',
    'Jutland, Denmark',
    'Tatarstan',
    'private',
    'WIWWWwis',
    'TTamilnade',
    'jajtJack',
    'Grand Cayman',
    'Florida(FL)',
    'United States â€\x8f(â€Ž+1)',
    'papa',
    'W/i',
    'CAc',
    'GUA',
    'SF',
    'Boston, MA',
    'Virgin Islands',
    'Nova ScotiaN',
    'UP',
    'Te',
    'India',
    'Nh',
    'Calif',
    'Lasnamäe linnaos',
    'NVNN',
    'SELECT FROM LIST',
    'Slovenia',
    'Tampa',
    'LIMA DEPARTAMENTO',
    'cairo',
    'MM',
    'De',
    'Country other than US or CA',
    'NT',
    'Region 11',
    'east sussex',
    'ilil',
    'NeNn',
    'Merseyside',
    'Kuching',
    'AS',
    'antofagasta',
    'Jawa Barat',
    'DKI Jakarta',
    'City of Kigali',
    'National Capital District',
    'caracas',
    'Samutsakorn',
    'Osrednjeslovenska',
    'ARRIYADH',
    'maharashtra',
    'WELLINGTON',
    'Bay Islands',
    'Stockton On Tees',
    'Kingston 5',
    'Italy',
    'CTc',
    'LND',
    '4/8/2020 11:03',
    'as',
    '4/8/2020 21:44',
    'US/MI',
    'Aruba',
    'Salem OR',
    'DC - District of Columbia',
    'Barishal',
    'Lagos state',
    '5/7/2020 15:04',
    'accra',
    '4/26/2020 16:17',
    'PhiP',
    'arkansasArkansas',
    'Bangalore',
    '4/21/2020 6:28',
    'Pleasant Prairie',
    '5/6/2020 12:52',
    'Andere',
    'Only',
    'Otro',
    'suss',
    'BCN',
    '4/8/2020 12:21',
    'MadisMaM',
    'Slovakia',
    '4/16/2020 10:21',
    'Reykjavik',
    'chucagi',
    'Autre',
    'sk',
    'GUADALAJARA',
    'jalisco',
    'Costa Rica',
    'Assam',
    'Islamabad Capital Territory',
    'Wrexham',
    "T'ai-pei city", 'Bogota D.C',
    'Buenos Aires Province',
    'BKM',
    'Reading',
    'Al Iskandariyah',
    'Gurgaon',
    'DU',
    'shibuya',
    'ciudad de mexico',
    'FR',
    'UTTAR PRADESH',
    'Not Applicable',
    '13',
    '105',
    'Dubayy',
    'SPAIN',
    'DL',
    'South Africa',
    'Distrito Federal',
    'London City of',
    'gujarat',
    'HR',
    'HARYANA',
    'Mahastra/New York',
    'France',
    'MUSCAT',
    'CAA',
    'Coast',
    '4/16/2020 16:37',
    'Region Metropolitana (RM)',
    'Jawa Timur',
    'Hawalli',
    'NLE',
    'Bagmati',
    'DIF',
    'Wilmington',
    'edo. de mexico',
    'Mokattam',
    'Saint Philip',
    'Najd',
    'Trelawny Parish',
    'KV',
    'jeddah',
    'Western Urban',
    'BR',
    'Ash Sharqiyah (Eastern Province)',
    'WP KL',
    'riyadh',
    'Ile de france',
    'Greater Accra Region',
    'northeast',
    'CE',
    'Erongo',
    'Moscow (City)',
    'Jawa Tengah',
    'Attica',
    'Central and Western Hong Kong Island',
    'Armed Forces Pacific',
    'VD',
    'Colombo',
    'Pangasinan',
    'Cordoba',
    'Rayong',
    'Mississauga',
    'Tiba (Chiba)',
    'PB',
    'Add State',
    'Al Ahmadi',
    'Kwara',
    'St. Catherine',
    'Kiev',
    'Niamey',
    'BJ',
    'Hong Kong',
    'Fejer',
    'Dar es salaam',
    'PS',
    'Kingston Parish',
    'TV',
    'Tai Po New Territories',
    'Luxembourg',
    '\\--',
    'Ghana',
    'Saint George Basseterre',
    'Belgium',
    'CHS',
    'punjab',
    'metro manila',
    'Miranda',
    'ACCRA',
    'MAharashtra',
    'Ad Dawhah',
    'Casablanca',
    'SL',
    'Bet Shemesh',
    'Prathumthani',
    'Abu Zaby',
    'Bogotá D.C.',
    'GT',
    'NP',
    'Tunapuna/Piarco',
    'DKI',
    'Catch All',
    'TP',
    'CDM',
    'BDC',
    'Telengana',
    'ABU DHABI',
    'GR',
    'Please add info',
    'G',
    'Tamaulipas',
    'Al Jizah',
    'kuwait',
    'JR',
    'ZA',
    'Add state',
    'Noord',
    'Kinondoi',
    'Lusaka Province',
    'Please select',
    'Al Qahirah',
    '\\---',
    ' -- select --',
    'Jakarta Raya',
    'NRB',
    '5/13/2020 23:28',
    'S',
    '74',
    'Not USA/Canada',
    'Spore',
    'Zuid Holland',
    'WGN',
    'Eastern',
    'ROO',
    'merkaz hacarmel',
    'Barnet',
    'Vilnius',
    'Rivers',
    'Highland',
    'KL',
    'district 2',
    'Kagera',
    'TEH',
    'Aguascalientes',
    'RS',
    'ML',
    'Sandys',
    'other',
    'NEW SOUTH WALES',
    'Male',
    'Russia',
    'Washington, DC',
    'PP',
    'St. James',
    'NW',
    'Mesaieed',
    'Jammu and Kashmir',
    'Baltimore MD',
    'Borno State',
    'TO',
    'Sc',
    'St Croix',
    'italy',
    'Dar es  salaam',
    'new providence',
    '48312',
    'bkk',
    'Guayas',
    'Sofia',
    'CDC',
    'DA',
    '21204',
    "'Ajman", 'Graubunden',
    'FLFl',
    'Odesa',
    'DW',
    'Western Region',
    'Jiangxi',
    'Saint James Parish',
    'Brandenburg',
    'Tripoli District',
    'MOW',
    'IowaIA',
    'GJ',
    'Ashanti Region',
    'RD',
    'Hidalgo\xa0*',
    'Oyo state',
    "L'viv", 'MONTSERRADO',
    'Basel-Stadt',
    '8b',
    "'- None -", 'Tucuman',
    'Ciudad de Buenos Aires',
    'Brasov',
    'Chihuahua',
    'Bucuresti',
    'Osun',
    'CVVanc',
    'Almaty',
    'Northwest Territories',
    'B',
    'Menges',
    'Cayman Islands',
    'WC',
    'West Yorkshire',
    'CC',
    'OLF',
    'SH',
    'LI',
    'Ras Tanura',
    '3rd',
    'Saint George',
    'Kwun Tong Kowloon',
    'BEN',
    'MDMD',
    'China',
    'CAM',
    'TX`',
    'Sheffield',
    'VOV',
    'KOREA',
    'HEA',
    'Outside US',
    'Kwai Tsing New Terri',
    'PY',
    'Agusan del Norte',
    'SPE',
    'Eastern Region',
    'Los Lagos (X)',
    '4',
    'please fill out',
    'FFL',
    '75039',
    '75211-7412',
    'MAPUTO',
    'NJN',
    'test',
    'SA',
    'Raleigh',
    'Southern Province',
    '75219',
    'Nagano',
    'Gainesville',
    'IN.',
    'Azadegan',
    'Maharsathra',
    'Paris',
    'Jhgf',
    'MASSACHUSETTS',
    'PUE',
    '75243',
    'Please select a region, state or province.',
    '76102',
    'NYN',
    'Onttario',
    'Alta',
    'ALA',
    'Samut Sakhon',
    'CANTABRIA',
    '75201-1803',
    'International/Other',
    '75034-1885',
    'Belgique',
    'alberta',
    '75201-2031',
    '75254-2949',
    '75240-2615',
    'Non-US/Other',
    'HC',
    'ACT',
    'shanghai',
    '75074-5570',
    'Pahang',
    '75219-3217',
    '其他',
    'Suva',
    '76116',
    'WP',
    '75201-4733',
    'Ann Arbor',
    '75217',
    'Pirkanmaa',
    '76107-2352',
    'Islands New Territories',
    '76101-0970',
    '75024-2114',
    'Switzerland',
    'SR',
    'Rochester, New York',
    'Bayern',
    'San Juan/Laventille',
    'Sassss',
    'HKI',
    '75201-2899',
    '75201-2300',
    'HE',
    'T',
    '75062-4831',
    '75201-2900',
    'MinnMinneosaMArden Hills',
    'AZMma',
    '75201-3302',
    '75023-1752',
    '76148',
    '76102-6312',
    '75038',
    '75201',
    '75230',
    'KOW',
    'NSWNSWE',
    'São Joses dos Pinhias/Parana',
    'N/c',
    'Atlanta GA',
    '75206-0500',
    '75201-6915',
    '75209-5715',
    'CGV',
    'QHR',
    'Port of Spain',
    'Bratislava',
    'Lothians',
    '75204',
    'Marupes novads',
    'XXXXX',
    '1082MA',
    'Pennsylvania (PA)',
    'Lanarkshire',
    'Yesenia',
    'Newcastle upon Tyne',
    'Sask',
    'Cape Town',
    '1',
    'San Isidro',
    'Columbia, Maryland',
    'BY',
    'LAGOS NIGERIA',
    'Santarém',
    'Garden City',
    'Sant cugat',
    'Newfoundland',
    'Altamonte Springs',
    'Barbados',
    'CABA',
    'RegiÃ³n Metropolitana',
    'Pasig',
    'ONOo1OOn',
    'QO',
    'CA-AB',
    'NEBRASKA',
    '5/12/2020 6:54',
    'QuâˆšÂ©bec',
    'ILILKLIllinois',
    'W',
    'Boca Raton',
    'PapPan',
    'Australian Capital Territories',
    'Flf',
    'Me',
    'Veneto',
    'BRU',
    'Quindio',
    'BelgiÃ«',
    'MX-CMX',
    'Mountain View, CA',
    'NY,',
    'abu dhabAbud dhabtUAtce',
    'Norfolk',
    'AU',
    'Prague 4',
    'Bv',
    'dc',
    'MEXICO',
    'LouLouisi',
    'TeTTX',
    'SSinga',
    'md',
    'RABAT SALE KENITRA',
    'Berks',
    'N',
    'Serbia',
    '76104',
    '76134-2001',
    '76134-2099',
    '75039-3726',
    '75057',
    'HA',
    'NewN',
    'Rochester',
    'Indonesia',
    '75261',
    'ohioohio',
    '75075-7738',
    '76107-2553',
    'Folsom',
    'C',
    'CCaliforn',
    'CACCCA',
    'Hauts de Seine',
    '232855015',
    '75287',
    '75063-2578',
    '75251',
    'JAKARTA',
    '98101',
    'RenRen',
    'LOUISIANA',
    'CA-ON',
    'MG',
    '37',
    'Milano',
    'IS',
    'WLV',
    'N/A (Outside US or CA)',
    'VIrginia',
    'Yvelines',
    'Vicente Lopez',
    'Cajamarca',
    'Curacao',
    'Aichi',
    '76118',
    'Nn',
    '75035',
    '75228',
    '75231',
    'Z',
    'A',
    'Madhyapradesh',
    'Phase 1',
    'abc',
    'Cavite',
    'NEnNebraska',
    '200',
    'ManiotbaMBdsd15',
    'Bataan',
    'uusimaa',
    'UAE',
    '394',
    'WWwiW',
    'WiscWisconwWisconsin',
    'Lake',
    'Panamá',
    'KOGI STATE',
    'O',
    'MO Missouri',
    'NENENebraska',
    'Alberta, Canada',
    'CCa',
    '*Not Listed',
    'OntariON',
    'OHOOOJHOOSOOOOOHIO',
    'PENNSYLVANIA',
    'Davao City, Davao del Sur',
    'Centurion',
    'West Bay',
    'Brighton and Hove',
    'north Carolina',
    'Fulton County',
    'Greater Minneapolis-St. Paul Area',
    'Mansfiel',
    'JM',
    'TXTexas',
    'ILE de France',
    'Capital Territory',
    'GB',
    'ghf',
    'Gujurat',
    '...',
    'D√ºsseldorf',
    'a',
    '5/4/2020 11:52',
    'Little Rock',
    '4/10/2020 19:30',
    'Outra',
    '4/15/2020 11:04',
    '4/9/2020 5:18',
    'Vestfold',
    'Wolverhampton',
    'Pune',
    'TamilNadu',
    'Sangre Grande',
    'Sughd',
    'DSU',
    'NYK',
    'FS',
    'CBL',
    'State of Rio de Janeiro',
    'ChinaEmptyState',
    'Masqat',
    'Derbyshire',
    'BA',
    'Hk',
    'DXB',
    'muscat',
    'Brisbane',
    'Isle of Man',
    'TAM',
    'Milan',
    'GLG',
    'ABE',
    'BAS',
    'Kabul province',
    'Brong-Ahafo Region',
    'Kalimantan Timur',
    'Hauts-de-Seine',
    'singapore',
    'Seoul Special City',
    'Hebei',
    'SZ',
    'TU',
    'Wien',
    'Federated States of Micronesia',
    'WE',
    'Saudi Arabia',
    'Trinidad and Tobago',
    'Al Bahah',
    'Al Ghuwayriyah',
    'Laguna',
    'BDF',
    'Marshall Islands',
    '75202-4206',
    '75063',
    '761022802',
    '75230-2856',
    '76106-7508',
    '75034-5977',
    '761312830',
    '75034',
    '75024-3525',
    '75254',
    '75220-8108',
    '76117-6139',
    '76131',
    '76101',
    '76131-2830',
    '29501',
    '75205',
    '75220',
    '75207-2401',
    'NZ',
    '60606',
    '75024',
    'ri',
    '75201-2517',
    'Ban',
    '75237',
    '75024-4006',
    'Shanxi',
    '752511245',
    '76155',
    '75202',
    '76112',
    '75231-5027',
    'Hafnarfjörður',
    '75398',
    '21',
    '75201-7675',
    'Andaman and Nicobar',
    '75265-5147',
    '75063-3119',
    '75235-1908',
    'plovdiv',
    '76102-6803',
    'Austin, TX',
    '10036',
    '75028',
    '44115-1093',
    '75230-2544',
    '76134',
    '75240',
    '75024-7145',
    '75039-2422',
    '75248',
    'EverettEv',
    '75243-3714',
    '75024-7111',
    'Korea',
    '75230-2501',
    '75254-1378',
    'Colombia',
    '76137',
    '08807-1265',
    '75063-3205',
    '75024-5837',
    'BIR',
    'Noida Area',
    'America',
    '76179-3505',
    '76107',
    '20817',
    '76179',
    'County Galway',
    'NORTHnc',
    'DCDCDCdd',
    'Kano state',
    'Madison, WI',
    'CalicaCA',
    'PA-Pennsylvania',
    'gGe',
    'Ab',
    'xxx',
    'Cascais ',
    'SuBBrB',
    'CChantilly Chantilly',
    'MD - Maryland',
    'Kampala',
    'Tyumen area',
    'Pittsburgh',
    'Ks',
    'Czech Republic',
    'Baden-WÃ¼rttemberg',
    '75266',
    'Somerset',
]
print(lst)